spring:
  config:
    activate:
      on-profile: dev
    import:
      - application-jwt.yaml
      - application-oauth.yaml
  datasource:
    url: jdbc:mariadb://liquor-business-db.cdi4cweas6u0.ap-northeast-2.rds.amazonaws.com:3306/liquor_business??useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    open-in-view: false