spring:
  config:
    activate:
      on-profile: local
    import:
      - application-jwt.yaml
      - application-oauth.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/liquor_business?useUnicode=true&characterEncoding=UTF-8
    username: ${DATABASE_USERNAME}
    password: ${LOCAL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false