spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${Kakao_OAuth_Client_ID}
            client-secret: ${Kakao_OAuth_Client_Secret}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id